# Generated by Django 4.1.7 on 2023-09-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_auto_20230922_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimateItems',
        ),
    ]
