# Generated by Django 4.1.7 on 2023-09-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_estimates_estimateitems_estimate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='terms',
        ),
        migrations.DeleteModel(
            name='sales_item',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
