# Generated by Django 4.1.7 on 2023-10-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_retainerinvoice_retaineritems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='retainerinvoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retaineritems',
            name='retainer',
        ),
        migrations.DeleteModel(
            name='retainer_invoice_comments',
        ),
        migrations.DeleteModel(
            name='RetainerInvoice',
        ),
        migrations.DeleteModel(
            name='Retaineritems',
        ),
    ]
