# Generated by Django 4.1.7 on 2023-10-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0021_retainer_payment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='retainer_payment_details',
        ),
    ]
