# Generated by Django 4.1.7 on 2023-10-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='settings',
        ),
    ]
