# Generated by Django 4.1.7 on 2023-10-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_setting_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='setting_list',
        ),
    ]
