# Generated by Django 4.1.7 on 2023-10-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0038_invoice_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invoice_item',
        ),
    ]
