# Generated by Django 4.1.7 on 2023-10-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0046_invoice_invoice_item_invoice_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitems',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='user',
        ),
        migrations.DeleteModel(
            name='estimate_comments',
        ),
        migrations.DeleteModel(
            name='EstimateItems',
        ),
        migrations.DeleteModel(
            name='Estimates',
        ),
    ]
