# Generated by Django 4.1.7 on 2023-10-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0048_estimates_estimateitems_estimate_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='retainer_payment_details',
        ),
    ]
