# Generated by Django 4.1.7 on 2023-10-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0050_retainer_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retainer_payment_details',
            name='retainer',
        ),
        migrations.RemoveField(
            model_name='retainer_payment_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retaineritems',
            name='retainer',
        ),
        migrations.DeleteModel(
            name='retainer_invoice_comments',
        ),
        migrations.DeleteModel(
            name='retainer_payment_details',
        ),
        migrations.DeleteModel(
            name='Retaineritems',
        ),
    ]
