# Generated by Django 4.1.7 on 2023-10-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0051_remove_retainer_payment_details_retainer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetainerInvoice',
        ),
    ]
